export const tickets = {
  success: true,
  code: 200,
  message: 'OK',
  data: [
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-23',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-23',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-23',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-23',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-23',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-23',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-24',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-24',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-24',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-24',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-24',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-24',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-25',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-25',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-25',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-25',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-25',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-25',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-26',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-26',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-26',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-26',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-26',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-26',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-27',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-27',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-27',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-27',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-27',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-27',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-28',
      price: 439.0,
      ratio: 0.943,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-28',
      price: 350.0,
      ratio: 0.943,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-28',
      price: 350.0,
      ratio: 0.943,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-28',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-28',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-28',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-29',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-29',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-29',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-29',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-29',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-29',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-30',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-30',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-30',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-30',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-30',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-30',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-31',
      price: 499.0,
      ratio: 0.94,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-31',
      price: 399.0,
      ratio: 0.94,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-31',
      price: 399.0,
      ratio: 0.94,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-31',
      price: 439.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-31',
      price: 339.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-31',
      price: 339.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-01',
      price: 499.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-01',
      price: 399.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-01',
      price: 399.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-01',
      price: 439.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-01',
      price: 339.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-01',
      price: 339.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-02',
      price: 549.0,
      ratio: 0.94,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-02',
      price: 439.0,
      ratio: 0.94,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-02',
      price: 439.0,
      ratio: 0.94,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-02',
      price: 489.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-02',
      price: 379.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-02',
      price: 379.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-03',
      price: 499.0,
      ratio: 0.94,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-03',
      price: 399.0,
      ratio: 0.94,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-03',
      price: 399.0,
      ratio: 0.94,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-03',
      price: 439.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-03',
      price: 339.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-03',
      price: 339.0,
      ratio: 0.95,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-04',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-04',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-04',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-04',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-04',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-04',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-05',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-05',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-05',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-05',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-05',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-05',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-06',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-06',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-06',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-06',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-06',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-06',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-07',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-07',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-07',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-07',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-07',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-07',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-08',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-08',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-08',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-08',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-08',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-08',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-09',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-09',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-09',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-09',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-09',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-09',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-10',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-10',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-10',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-10',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-10',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-10',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-11',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-11',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-11',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-11',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-11',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-11',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-12',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-12',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-12',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-12',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-12',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-12',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-13',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-13',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-13',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-13',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-13',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-13',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-14',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-14',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-14',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-14',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-14',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-14',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-15',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-15',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-15',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-15',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-15',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-15',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-16',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-16',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-16',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-16',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-16',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-16',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-17',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-17',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-17',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-17',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-17',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-17',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-18',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-18',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-18',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-18',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-18',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-18',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-19',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-19',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-19',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-19',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-19',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-19',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-20',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-20',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-20',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-20',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-20',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-20',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-21',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-21',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-21',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-21',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-21',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-21',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-22',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-22',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-22',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-22',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-22',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-22',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-23',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-23',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-23',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-23',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-23',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-23',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-24',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-24',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-24',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-24',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-24',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-24',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-25',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-25',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-25',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-25',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-25',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-25',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-26',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-26',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-26',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-26',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-26',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-26',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-27',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-27',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-27',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-27',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-27',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-27',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-28',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-28',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-28',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-28',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-28',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-28',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-29',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-29',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-29',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-29',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-29',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-29',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-30',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-30',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-30',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-30',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-30',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-30',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-31',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-31',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-31',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-31',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-31',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-31',
      price: 290.0,
    },
  ],
};
