export const tickets = {
  success: true,
  code: 200,
  message: 'OK',
  data: [
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-11',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-11',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-11',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-11',
      currency: 'CNY',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-11',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-11',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-12',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-12',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-12',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-12',
      currency: 'CNY',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-12',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-12',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-13',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-13',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-13',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-13',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-13',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-13',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-14',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-14',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-14',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-14',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-14',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-14',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-15',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-15',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-15',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-15',
      currency: 'CNY',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-15',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-15',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-16',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-16',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-16',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-16',
      currency: 'CNY',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-16',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-16',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-17',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-17',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-17',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-17',
      currency: 'CNY',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-17',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-17',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-18',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-18',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-18',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-18',
      currency: 'CNY',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-18',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-18',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-19',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-19',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-19',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-19',
      currency: 'CNY',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-19',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-19',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-20',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-20',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-20',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-20',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-20',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-20',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-21',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-21',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-21',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-21',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-21',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-21',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-22',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-22',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-22',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-22',
      currency: 'CNY',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-22',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-22',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-23',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-23',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-23',
      currency: 'CNY',
      price: 300.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-23',
      currency: 'CNY',
      price: 319.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-23',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-23',
      currency: 'CNY',
      price: 240.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-24',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-24',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-24',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-24',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-24',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-24',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-25',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-25',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-25',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-25',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-25',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-25',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-26',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-26',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-26',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-26',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-26',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-26',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-27',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-27',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-27',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-27',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-27',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-27',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-28',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-28',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-28',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-28',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-28',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-28',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-29',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-29',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-29',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-29',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-29',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-29',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-30',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-30',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-30',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-30',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-30',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-30',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-31',
      currency: 'CNY',
      price: 499.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-31',
      currency: 'CNY',
      price: 399.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-31',
      currency: 'CNY',
      price: 399.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2025-12-31',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2025-12-31',
      currency: 'CNY',
      price: 339.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2025-12-31',
      currency: 'CNY',
      price: 339.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-01',
      currency: 'CNY',
      price: 499.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-01',
      currency: 'CNY',
      price: 399.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-01',
      currency: 'CNY',
      price: 399.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-01',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-01',
      currency: 'CNY',
      price: 339.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-01',
      currency: 'CNY',
      price: 339.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-02',
      currency: 'CNY',
      price: 549.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-02',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-02',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-02',
      currency: 'CNY',
      price: 489.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-02',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-02',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-03',
      currency: 'CNY',
      price: 499.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-03',
      currency: 'CNY',
      price: 399.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-03',
      currency: 'CNY',
      price: 399.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-03',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-03',
      currency: 'CNY',
      price: 339.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-03',
      currency: 'CNY',
      price: 339.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-04',
      currency: 'CNY',
      price: 439.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-04',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-04',
      currency: 'CNY',
      price: 350.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_ADULT',
      travelDate: '2026-01-04',
      currency: 'CNY',
      price: 379.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_CHILD',
      travelDate: '2026-01-04',
      currency: 'CNY',
      price: 290.0,
    },
    {
      touristResortTicketsCategoryFullCode: 'SHANGHAI_LEGOLAND_EARLY_ONE_DAY_ONE_SENIOR',
      travelDate: '2026-01-04',
      currency: 'CNY',
      price: 290.0,
    },
  ],
};
